vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        service:
            uri_prefix: /images/image_service
            upload_destination: '%kernel.project_dir%/public/images/image_service'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer